import React from "react";
import { apCount, apDate, millions } from "../format";

// Every reader-facing sentence on the page. Keys are grouped by where they
// appear. Figures arrive formatted ("$1,848.08", "6.76%", years as numbers);
// a function only arranges words around them. Running text follows AP style.

export default {
  // ---- formats
  "fmt.today": (date) => date.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }),
  "fmt.date": (ymd) => apDate(ymd),
  "fmt.millions": (n) => millions(n),
  "fmt.aboutMillions": (n) => `$${(n / 1e6).toFixed(2)} million`,

  // ---- page states
  "load.loading": "Loading the budget…",
  "load.errorTitle": "The budget data could not be loaded.",
  "load.errorBody": (email) => <>Reload the page to try again. If it keeps happening, email <a href={`mailto:${email}`}>{email}</a>.</>,
  "status.proposed": "Mayor’s proposed budget. Not yet adopted.",

  // ---- masthead and banner
  "flag.homeAria": "Wausau Pilot & Review home",
  "banner.kicker": "City of Wausau",
  "banner.title": (year) => <>Follow the Money: Wausau&rsquo;s {year} budget</>,
  "banner.dek": ({ levy, pct, spend }) => `The proposal would raise ${levy} in property taxes, up ${pct}, and spend ${spend} on police, fire, streets, parks and city hall. Here is what it means for your bill.`,
  "sponsor.presentedBy": "Presented by",

  // ---- calculator
  "calc.assessedLabel": "Assessed value of your property",
  "calc.example": "This is an example. ",
  "calc.hint": "Use the assessed value on your tax bill, not the market value.",
  "calc.yourTax": (year) => `Your ${year} city tax`,
  "calc.compare": ({ diff, prior, year }) => <><span className="calc-diff">{diff}</span> from {prior} in {year}</>,
  "calc.empty": "Type the assessed value from your tax bill.",
  "calc.rate": ({ rate, dir, prev }) => `${rate} per $1,000 of assessed value, ${dir === "up" ? "up from" : dir === "down" ? "down from" : "the same as"} ${prev}.`,
  "calc.jump": (bill) => `See where your ${bill} goes`,
  "card.full": "See the full budget breakdown",
  "share.button": "Share",
  "share.copied": "Link copied",
  "share.urlAria": "Link to share",
  "share.title": (year) => `Follow the Money: Wausau’s ${year} budget`,
  "share.text": ({ dir, home, diff, year }) => `Wausau’s proposed ${year} budget would ${dir === "up" ? "raise" : "lower"} the city tax on a ${home} home by ${diff}. See what it means for yours:`,

  // ---- section nav
  "nav.aria": "Sections",
  "nav.bill": "Your bill",
  "nav.levy": "The levy",
  "nav.general-fund": "General fund",
  "nav.departments": "Departments",
  "nav.fees": "Fees",
  "nav.capital": "Projects",
  "nav.debt": "Debt",
  "nav.reserves": "Reserves",
  "nav.staffing": "Staffing",
  "nav.about": "About",

  // ---- updates
  "updates.title": "Changes since the proposal",
  "updates.note": "The figures below are the mayor’s proposal. These are the changes made since, newest first.",
  "updates.read": "Read the story",

  // ---- highlights
  "hl.title": "What’s in the proposal",
  "hl.levy": ({ since, first }) => (since ? `levy increase, the largest since ${since}` : `levy increase, the largest since at least ${first}`),
  "hl.requestsFig": ({ below, total }) => `${below} of ${total}`,
  "hl.requests": (above) => `budgets came in below what was requested; ${apCount(above)} came in above`,
  "hl.admin": "for a proposed city administrator",
  "hl.fees": (up) => `fee changes; ${apCount(up)} go up`,

  // ---- reader-facing fund labels: [label, description, short form for the flow]
  "fund.General Fund.label": "Day-to-day services",
  "fund.General Fund.desc": "Police, fire, streets, parks and city hall",
  "fund.General Fund.short": "Day-to-day",
  "fund.Debt Service Fund.label": "Debt payments",
  "fund.Debt Service Fund.desc": "Principal and interest on money the city has borrowed",
  "fund.Debt Service Fund.short": "Debt",
  "fund.MetroRide Fund.label": "Metro Ride",
  "fund.MetroRide Fund.desc": "The city bus system",
  "fund.MetroRide Fund.short": "Metro",
  "fund.Recycling Fund.label": "Recycling",
  "fund.Recycling Fund.desc": "Curbside recycling",
  "fund.Recycling Fund.short": "Recycling",
  "fund.Central Equipment Capital Fund.label": "Equipment and small facility work",
  "fund.Central Equipment Capital Fund.desc": "Police cameras, radios and vests; computers and phones; small building repairs",
  "fund.Central Equipment Capital Fund.short": "Equipment",
  "fund.Community Development.label": "Community development",
  "fund.Community Development.desc": "Planning, economic development and housing programs",
  "fund.Community Development.short": "Planning",
  "fund.Capital Projects Fund.label": "Streets and construction",
  "fund.Capital Projects Fund.desc": "The tax-funded share of street, sidewalk and building projects",
  "fund.Capital Projects Fund.short": "Streets",
  "fund.Wausau Downtown Airport Fund.label": "Downtown airport",
  "fund.Wausau Downtown Airport Fund.desc": "Wausau Downtown Airport operations",
  "fund.Wausau Downtown Airport Fund.short": "Airport",
  "fund.Parking Fund.label": "Parking",
  "fund.Parking Fund.desc": "City ramps and lots",
  "fund.Parking Fund.short": "Parking",
  "fund.Animal Control.label": "Animal control",
  "fund.Animal Control.desc": "Animal control services",
  "fund.Animal Control.short": "Animals",
  "fund.tif.label": "Tax increment districts",
  "fund.tif.desc": "Taxes on new development in the city’s TIF districts, set aside for those districts’ costs",
  "fund.tif.short": "TIF",

  // ---- your bill
  "bill.title": (bill) => `Follow your ${bill}`,
  "bill.standfirst": "Your city tax, to scale: first the funds it pays for, then an estimate of how day-to-day services split it among departments. Hover or tap a block for its share.",
  "bill.flowShort": "Your city tax",
  "bill.flowAria": ({ bill, funds, rest, depts }) => `Your ${bill} city tax: ${funds.map((f) => `${f.amount} to ${f.label.toLowerCase()}`).join(", ")}, and the rest to ${rest} smaller funds. Of day-to-day services, ${depts.map((d) => `${d.label.toLowerCase()} ${d.amount}`).join(", ")}. Every amount is listed below.`,
  "bill.tipFund": "of your city tax",
  "bill.tipDept": "of day-to-day services (estimate)",
  "bill.flowNote": "The bottom row is an estimate: it splits day-to-day services by each department’s share of general fund spending. The city pools property taxes with state aid and fees; it does not assign tax dollars to departments.",
  "bill.preliminary": ({ year, growth }) => <><b>The {year} rate is preliminary.</b> It rests on the city&rsquo;s placeholder for {year} assessed value (last year&rsquo;s plus {growth}), which will change when the state publishes final figures.</>,
  "bill.receiptTitle": "Every line of your city tax",
  "bill.receiptTotal": (year) => `City share of your ${year} bill`,
  "bill.receiptNote": (year) => `Each line is that fund’s share of the full ${year} city levy, including tax increment districts. Lines are rounded to the cent, so they can differ from the total by a few cents.`,
  "bill.cityOnly": <><b>This is only the city&rsquo;s part of your bill.</b> Your full property tax bill also includes Marathon County, your school district and the technical college, whose rates are set in mid-November. Both years use the same assessed value; if your assessment changed, your actual change will differ.</>,

  // ---- shared bits
  "change.new": "new",
  "change.none": "no change",
  "table.year": "Year",
  "table.total": "Total",
  "table.change": "Change",

  // ---- levy
  "levy.title": "Where the levy goes, year by year",
  "levy.standfirst": ({ total, year, up, pct, prev, first, grown }) => `The city plans to collect ${total} in property taxes for ${year}, up ${up} (${pct}) from ${prev}. Since ${first} the levy has grown ${grown}.`,
  "levy.swingTitle": ({ dir, amount }) => `Where the ${amount} ${dir === "up" ? "increase" : "decrease"} comes from`,
  "levy.swingNote": ({ prev, year }) => `Each fund’s change in levy from ${prev} to ${year}; together they make up the whole change. Funds whose levy did not change are left out.`,
  "levy.swingTotal": "Total change",
  "levy.historyTitle": ({ first, last }) => `The levy by year, ${first} to ${last}`,
  "levy.otherFunds": "All other funds",
  "levy.totalLabel": "Total levy",
  "levy.chartAria": ({ first, last, from, to }) => `Stacked column chart of the city property tax levy by year, ${first} to ${last}, rising from ${from} to ${to}. The same figures are in the table below.`,
  "levy.tableTitle": "Total levy by year",
  "levy.colTotal": "Total levy",
  "levy.fundsTitle": "Every fund the levy pays for",
  "levy.fundsNote": ({ first, last, year }) => `Bars show ${first} to ${last}, each row on its own scale. The amount is the ${year} levy.`,
  "levy.sparkAria": ({ label, first, last }) => `${label}, ${first} to ${last}`,
  "levy.noneSince": (year) => `none since ${year}`,
  "levy.limitTitle": "The state limit, and what it leaves out",
  "levy.limitBody": ({ year, allowable, debt, actual }) => `Wisconsin caps how much a city’s levy can grow, but payments on borrowed money are exempt. For ${year}, the limit allows ${allowable}, plus ${debt} for debt payments. The proposed levy, not counting tax increment districts, is ${actual}.`,

  // ---- general fund
  "gf.title": <>The city&rsquo;s <span className="nowrap">day-to-day</span> budget</>,
  "gf.standfirst": ({ tax, share }) => `The general fund pays for police, fire, streets, parks and city hall. Property taxes cover ${tax} of it, about ${share} of its revenue.`,
  "gf.spending": "Spending",
  "gf.revenue": "Revenue",
  "gf.gap": "Spending minus revenue",
  "gf.from": (year) => `from ${year}`,
  "gf.gapNote": "planned spending exceeds revenue",
  "gf.viewAria": "General fund view",
  "gf.colDept": "Department",
  "gf.colSource": "Source",
  "gf.colProposed": (year) => `${year} proposed`,
  "gf.colShare": "Share",
  "gf.colVs": (year) => `vs. ${year}`,
  "gf.noteSpending": ({ year, prev }) => `Proposed ${year} spending compared with the ${prev} adopted budget. Full figures for each department are in the next section.`,
  "gf.noteRevenue": ({ year, prev }) => `Proposed ${year} revenue compared with the ${prev} adopted budget.`,
  "ogg.note": (cost) => `Citywide costs not assigned to a department, including ${cost} for a proposed city administrator. Its budget page also carries the general fund’s general revenues, including the property tax, which pay for every department. That money is not earned by this office.`,

  // ---- departments
  "dept.title": "What each department asked for, and got",
  "dept.standfirst": ({ n, current, budget }) => `All ${n} department and fund budgets in the book. Open one to see its ${current} budget, its ${budget} request, the proposed amount, where the money goes, and about 10 years of budgeted and actual spending.`,
  "dept.searchLabel": "Find a department or fund",
  "dept.searchPlaceholder": "Police, water, parks…",
  "dept.noMatch": (q) => <>No department or fund matches &ldquo;{q}&rdquo;.</>,
  "group.General Fund": "The city’s main operating budget: police, fire, public works, parks and city hall. Most of the property tax lands here.",
  "group.Special Revenue Funds": "Money set aside for a specific purpose, such as recycling, room tax or community development grants.",
  "group.Debt Service Fund": "Payments on the city’s general obligation borrowing, which property taxes back.",
  "group.Capital Projects Funds": "Construction and equipment, plus the tax increment districts’ spending on development.",
  "group.Internal Service Funds": "Accounts that bill other city departments for vehicles, insurance and employee benefits. The same dollars also show up in the departments they bill.",
  "group.Enterprise Funds": "Services paid for largely by the people who use them: water, sewer, buses, parking and the airport.",
  "dept.colBudget": "Budget",
  "dept.adopted": (year) => `${year} adopted`,
  "dept.requested": (year) => `${year} requested`,
  "dept.proposed": (year) => `${year} proposed`,
  "dept.reqNothing": (amount) => `Nothing was requested. The proposed budget includes ${amount}.`,
  "dept.reqSame": "The proposed budget matches the request.",
  "dept.reqChanged": ({ diff, pct, dir }) => `Changed from request: ${diff} (${pct} ${dir === "below" ? "below" : "above"} the request).`,
  "dept.spending": "Spending",
  "dept.revenue": "Revenue",
  "dept.colCategory": "Category",
  "dept.noRevenue": "This budget has no revenue table.",
  "dept.page": ({ printed, pdf }) => <>See the city&rsquo;s page: page {printed} of the budget book (page {pdf} of the PDF).</>,
  "dept.totalNote": ({ n, total }) => `Together the ${n} budgets propose ${total} in spending. That total counts some dollars twice: money moved from one city fund to another, and internal service funds that bill other departments, are counted in both places.`,

  // ---- 10-year history (inside each department)
  "hist.title": ({ first, last }) => <>Budget and actual spending, <span className="nowrap">{first}&ndash;{last}</span></>,
  "hist.budget": "Budget, as amended",
  "hist.actual": "Actual spending",
  "hist.proposed": (year) => `${year} proposed`,
  "hist.aria": ({ name, first, last, year, proposed }) => `${name}: budget and actual spending, ${first} to ${last}, measured from the city's chart, with the ${year} proposal of ${proposed}. The same figures are in the table below the chart.`,
  "hist.approx": (page) => `Approximate: measured from the city’s chart on page ${page} of the budget book.`,
  "hist.check": ({ year, measured, table }) => ` As a check, its ${year} actual measures about ${measured}; the city’s budget table says ${table}.`,
  "hist.flagCheck": ({ year, measured, table }) => `The chart’s ${year} actual measures about ${measured}; the city’s budget table says ${table}. `,
  "hist.showTable": "Show as a table",
  "hist.tableAria": (name) => `${name} budget and actual spending by year`,
  "hist.colBudget": "Budget (approx.)",
  "hist.colActual": "Actual (approx.)",
  "hist.none": "none",
  "hist.tipBudget": "Budget",
  "hist.tipActual": "Actual",

  // ---- fees
  "fees.title": (year) => `Fees that change in ${year}`,
  "fees.standfirst": ({ total, up, down, removed, restructured }) => {
    const clauses = [
      [up, "goes up", "go up"], [down, "goes down", "go down"],
      [removed, "fee is dropped", "fees are dropped"],
      [restructured, "pass becomes a flat price", "passes become a flat price"],
    ].filter(([n]) => n).map(([n, one, many]) => `${apCount(n)} ${n === 1 ? one : many}`);
    const kinds = clauses.length > 1 ? `${clauses.slice(0, -1).join(", ")} and ${clauses[clauses.length - 1]}` : clauses[0];
    return `The proposed fee schedule changes ${total} rates: ${kinds}. Most are parking permits and park, pool and event rentals.`;
  },
  "fees.leadTitle": "Largest increases, by percentage",
  "fees.colFee": "Fee",
  "fees.colRates": ({ prev, year }) => `${prev} → ${year}`,
  "fees.colChange": "Change",
  "fees.count": ({ n, up }) => (up === n ? `${n} ${n === 1 ? "increase" : "increases"}` : `${n} ${n === 1 ? "change" : "changes"}, ${up} up`),
  "fees.to": "to",
  "fees.none": "none",
  "fees.discounts": "discounts",
  "fees.dropped": "dropped",
  "fees.flat": "flat price",
  "fees.was": ({ year, text }) => `In ${year}: “${text}”`,
  "fees.unclearTitle": "Unclear in the city’s schedule",
  "fees.problemsTitle": "Problems in the city’s schedule",
  "fees.page": (page) => `(Page ${page}.)`,
  "fees.note": ({ range, prev, year }) => `From the fee schedules on pages ${range} of the budget book. Wausau Pilot & Review compared every row, ${prev} against ${year}, and checked each change against the printed page. Fees that did not change are not listed.`,
  "feeGroup.Public works charges": "Public works charges",
  "feeGroup.Parking": "Parking",
  "feeGroup.Finance and pet licenses": "Finance and pet licenses",
  "feeGroup.Parks, pools and events": "Parks, pools and events",
  "feeGroup.Police": "Police",

  // ---- capital projects
  "cap.title": "What the city plans to build and buy",
  "cap.standfirst": ({ count, total, year, deferred, deferredTotal, top, topAmount, topShare }) => `The proposed budget funds ${count} listed projects totaling ${total} in ${year}. The largest, listed as “${top},” costs ${topAmount}: ${topShare} of the total. Another ${deferred} requests, worth ${deferredTotal}, were left out.`,
  "cap.gap": ({ printed, diff, sum, page, context }) => <><b>A gap in the city&rsquo;s list.</b> The printed total, {printed}, is {diff} more than the projects listed, which add up to {sum} (page {page} of the budget book). {context}</>,
  "discrepancy.capital projects: Infrastructure": "The gap equals the cost of the Ethel Street reconstruction, which appears only in a second copy of this list later in the book.",
  "cap.fundingTitle": "How the projects are paid for",
  "cap.fundingNote": ({ total, page }) => `Funding sources as the city lists them, totaling ${total} (page ${page} of the budget book).`,
  "cap.deferredTitle": "Requested but left out",
  "cap.deferredNote": ({ total, page }) => `Projects departments asked for that are not in the proposed budget: ${total} in all (page ${page} of the budget book).`,

  // ---- debt
  "debt.title": "What the city owes, and who repays it",
  "debt.standfirst": ({ total, asOf, go, rate }) => `The city owed ${total} as of ${asOf}. Property taxpayers back ${go} of it; water and sewer customers repay the other ${rate} through their utility rates.`,
  "debt.taxBacked": "Backed by property taxes",
  "debt.taxBackedNote": ({ undrawn, counted }) => `General obligation debt drawn so far. Counting ${undrawn} in state loans approved but not yet drawn, ${counted} counts against the city’s legal borrowing limit.`,
  "debt.rateBacked": "Repaid by water and sewer customers",
  "debt.water": "Water utility",
  "debt.sewer": "Sewer utility",
  "debt.rateNote": "Revenue debt, repaid from utility bills rather than the property tax.",
  "debt.limitTitle": "The legal limit",
  "debt.meterAria": ({ counted, limit, pct }) => `${counted} of a ${limit} limit, ${pct} used`,
  "debt.counted": ({ counted, pct }) => <><b>{counted}</b> counted ({pct})</>,
  "debt.limit": (limit) => <>Limit <b>{limit}</b></>,
  "debt.limitNote": (share) => `State law caps a city’s general obligation debt at ${share} of its equalized property value. Water and sewer revenue debt does not count toward the limit.`,
  "debt.payTitle": "Paying it back",
  "debt.payNote": ({ first, last, total, principal, interest, by, share }) => `Scheduled payments on general obligation debt, ${first} to ${last}. In ${first} the city pays ${total}: ${principal} in principal and ${interest} in interest. By ${by} the city is scheduled to repay ${share} of the principal.`,
  "debt.principal": "Principal",
  "debt.interest": "Interest",
  "debt.totalPayment": "Total payment",
  "debt.chartAria": ({ first, last, total }) => `Stacked column chart of scheduled general obligation debt payments from ${first} to ${last}, falling from ${total} in ${first}. The same figures are in the table below.`,
  "debt.showTable": "Show the repayment schedule as a table",
  "debt.tableAria": "Repayment schedule",

  // ---- reserves and the vehicle fund
  "res.title": "What the city keeps in reserve",
  "res.standfirst": ({ year, balance, share, budgetYear, goal }) => `The general fund ended ${year} with ${balance} in unassigned reserves, ${share} of the ${budgetYear} general fund budget. The city’s fund balance policy sets a goal of ${goal}, as the Government Finance Officers Association recommends.`,
  "res.balanceTitle": ({ first, last }) => `Unassigned general fund reserves, ${first} to ${last}`,
  "res.legendBalance": "Reserves as a share of the budget",
  "res.legendGoal": (goal) => `City policy goal, ${goal}`,
  "res.balanceAria": ({ first, last, from, to, goal }) => `Column chart of unassigned general fund reserves as a share of the budget, ${first} to ${last}, from ${from} to ${to}, against a goal of ${goal}. The same figures are in the table below.`,
  "res.pairing": ({ year, budgetYear, page }) => `As in the city’s table, each year-end balance is measured against the general fund budget two years later: the ${year} balance against the ${budgetYear} budget (page ${page} of the budget book).`,
  "res.showTable": "Show the numbers",
  "res.colBalance": "Unassigned reserves",
  "res.colBudget": "Budget measured against",
  "res.colShare": "Share",
  "res.fleetTitle": "The vehicle fund",
  "res.fleetNote": ({ last, lastYear, peak, peakYear, first }) => `The Motor Pool Fund runs the city’s fleet: it buys, repairs and maintains nearly all city vehicles and equipment and bills departments for their use. Its working capital was ${last} at the end of ${lastYear}. The highest since ${first} was ${peak}, in ${peakYear}.`,
  "res.fleetAria": ({ first, last }) => `Column chart of the Motor Pool Fund’s working capital at the end of each year, ${first} to ${last}. The same figures are in the table below.`,
  "res.quoteSource": (page) => `The budget overview, page ${page}`,
  "res.colWorking": "Working capital",

  // ---- staffing
  "staff.title": "How many people the city employs",
  "staff.standfirst": ({ now, year, prev, prevYear, grew, from, to, first }) => `The proposed budget funds ${now} full-time-equivalent positions in ${year}, compared with ${prev} in ${prevYear}. ${grew} has grown the most since ${first}, from ${from} to ${to} positions.`,
  "staff.chartAria": ({ first, last }) => `Column chart of total full-time-equivalent positions by year, ${first} to ${last}.`,
  "staff.caveat": ({ oldest, council, without }) => `* ${oldest} is not comparable with later years: it is the only year that counts the ${council} council members (${without} positions without them).`,
  "staff.byDept": "By department",
  "staff.note": ({ first, last }) => `Bars show ${first} to ${last}, each row on its own scale. Blank years are blank in the city’s table. Parks has no row: under an agreement with the city, the Marathon County Parks Department runs Wausau’s parks.`,
  "staff.sparkAria": ({ name, first, last }) => `${name} positions, ${first} to ${last}`,
  "staff.onlyIn": (year) => `only in ${year}`,
  "staff.notListed": "not listed",

  // ---- about
  "about.title": "About these numbers",
  "about.sourceT": "Source",
  "about.sourceD": ({ year, pages, url }) => <>The City of Wausau&rsquo;s {year} proposed budget, as published in the {pages}-page packet for the city&rsquo;s Finance Committee. Page references on this page use the numbers printed in the budget book. The city posts its budget documents on its <a href={url} target="_blank" rel="noopener noreferrer">budget reports page</a>.</>,
  "about.methodT": "Method",
  "about.methodD": (n) => `Wausau Pilot & Review extracted every table from the book and checked each one against the totals the city printed and against the book’s other tables. The ${n} department and fund budgets add up exactly to the citywide totals. Where the book disagrees with itself, this page says so.`,
  "about.historyT": "The 10-year history is approximate",
  "about.historyD": "The book shows past budgets and spending only as charts. The yearly figures in each department’s history were measured from those drawings, so they are close but not exact. Every chart that can be checked matches the city’s own figure for its last year within a fraction of a percent of the chart’s scale; the two that cannot are labeled.",
  "about.rateT": "The rate is preliminary",
  "about.rateD": ({ year, rate, growth }) => `The ${year} rate of ${rate} per $1,000 divides the levy by the city’s placeholder for ${year} assessed value, which is last year’s plus ${growth}. It will change when the state publishes final values.`,
  "about.cityT": "The city’s part only",
  "about.cityD": "Your property tax bill also includes Marathon County, your school district and the technical college. Their rates are set in mid-November.",
  "about.allFundsT": (total) => `Why this page doesn’t lead with ${total}`,
  "about.allFundsD": "That is the city’s spending across all funds, but it counts some dollars twice: money moved between city funds, and internal service funds that bill other departments for vehicles, insurance and benefits. The levy and the general fund are the clearer measures.",
  "about.finalT": "Not yet final",
  "about.finalD": "These are the mayor’s proposals. The Finance Committee and the Common Council can change them before the council adopts the budget. Changes will be logged at the top of this page.",
  "about.correctionsT": "Corrections",
  "about.correctionsD": (email) => <>See something wrong? Email <a href={`mailto:${email}`}>{email}</a>.</>,
  "about.dataT": "The data",
  "about.dataD": (base) => <>Download the <a href={`${base}budget.json`} download>budget figures</a>, the <a href={`${base}fees.json`} download>fee changes</a> and the <a href={`${base}history.json`} download>10-year history</a> (JSON).</>,

  // ---- support band and footer
  "support.title": <>Built by <span className="nowrap">Wausau Pilot &amp; Review</span></>,
  "support.body": ({ pages, units }) => `We read the city’s ${pages}-page budget, checked all ${units} department and fund budgets against its totals, and will update this page as the Finance Committee and the Common Council change the plan. Wausau Pilot & Review is a nonprofit newsroom, and reader support keeps tools like this free.`,
  "support.button": "Support our journalism",
  "support.meetings": "Follow the budget meetings",
  "foot.data.proposed": (year) => `Data: City of Wausau ${year} proposed budget. Updated by hand as the budget is amended.`,
  "foot.notAffiliated": "Not affiliated with or endorsed by the City of Wausau.",
};
