import React from "react";

// Spanish (US). Translated from en.jsx; same keys, same parameters.
// "Usted" throughout; US number style kept; terms follow wpr-budget (levy = "impuesto", assessed value = "valor tasado"); counts 1–9 spelled out.

const MESES = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"];
const PALABRAS = ["cero", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve"];
// Counts: one through nine in words, 10 and up as figures. One is handled where it is used, for gender.
const num = (n) => (n >= 0 && n < 10 ? PALABRAS[n] : String(n));

export default {
  // ---- formats
  "doc.title": "Follow the Money: el presupuesto municipal de Wausau · Wausau Pilot & Review",

  "fmt.today": (date) => date.toLocaleDateString("es-US", { weekday: "long", day: "numeric", month: "long", year: "numeric" }),
  "fmt.date": (ymd) => `${ymd.d} de ${MESES[ymd.m - 1]} de ${ymd.y}`,
  "fmt.millions": (n) => (n < 0 ? "−" : "") + "$" + (Math.abs(n) / 1e6).toFixed(1) + " millones",
  "fmt.aboutMillions": (n) => `$${(n / 1e6).toFixed(2)} millones`,

  // ---- language
  "lang.label": "Idioma",
  "lang.namesNote": "Los nombres que publica la ciudad (departamentos, fondos, categorías del presupuesto, tarifas y proyectos) aparecen en inglés, tal como están impresos.",
  "lang.betaTitle": "El hmong es una traducción comunitaria, en versión beta.",
  "lang.betaBody": (email) => <>Algunas frases pueden ser imperfectas. Dígale a Wausau Pilot &amp; Review qué corregir: <a href={`mailto:${email}`}>{email}</a>.</>,

  // ---- page states
  "load.loading": "Cargando el presupuesto…",
  "load.errorTitle": "No se pudieron cargar los datos del presupuesto.",
  "load.errorBody": (email) => <>Vuelva a cargar la página para intentarlo de nuevo. Si sigue ocurriendo, escriba a <a href={`mailto:${email}`}>{email}</a>.</>,
  "status.proposed": "Presupuesto propuesto por la alcaldía. Aún no aprobado.",

  // ---- masthead and banner
  "flag.homeAria": "Inicio de Wausau Pilot & Review",
  "banner.kicker": "Ciudad de Wausau",
  "banner.title": (year) => <>Follow the Money: el presupuesto de Wausau para {year}</>,
  "banner.dek": ({ levy, pct, spend }) => `La propuesta recaudaría ${levy} en impuestos a la propiedad, un aumento del ${pct}, y gastaría ${spend} en policía, bomberos, calles, parques y oficinas municipales. Esto es lo que significa para su factura.`,
  "sponsor.presentedBy": "Presentado por",

  // ---- calculator
  "calc.assessedLabel": "Valor tasado de su propiedad",
  "calc.example": "Este es un ejemplo. ",
  "calc.hint": "Use el valor tasado que aparece en su factura de impuestos, no el valor de mercado.",
  "calc.yourTax": (year) => `Su impuesto municipal de ${year}`,
  "calc.compare": ({ diff, prior, year }) => <><span className="calc-diff">{diff}</span> frente a {prior} en {year}</>,
  "calc.empty": "Escriba el valor tasado que aparece en su factura de impuestos.",
  "calc.rate": ({ rate, dir, prev }) => `${rate} por $1,000 de valor tasado, ${dir === "up" ? "un aumento respecto a" : dir === "down" ? "una baja respecto a" : "sin cambio respecto a"} ${prev}.`,
  "calc.jump": (bill) => `Vea a dónde van sus ${bill}`,
  "share.button": "Compartir",
  "share.copied": "Enlace copiado",
  "share.urlAria": "Enlace para compartir",
  "share.title": (year) => `Follow the Money: el presupuesto de Wausau para ${year}`,
  "share.text": ({ dir, home, diff, year }) => `El presupuesto propuesto de Wausau para ${year} ${dir === "up" ? "aumentaría" : "reduciría"} en ${diff} el impuesto municipal de una casa de ${home}. Vea qué significa para la suya:`,

  // ---- section nav
  "nav.aria": "Secciones",
  "nav.bill": "Su factura",
  "nav.levy": "El impuesto",
  "nav.general-fund": "Fondo general",
  "nav.departments": "Departamentos",
  "nav.fees": "Tarifas",
  "nav.capital": "Proyectos",
  "nav.debt": "Deuda",
  "nav.staffing": "Personal",
  "nav.about": "Acerca de",

  // ---- updates
  "updates.title": "Cambios desde la propuesta",
  "updates.note": "Las cifras de esta página son las de la propuesta de la alcaldía. Estos son los cambios hechos desde entonces, del más reciente al más antiguo.",
  "updates.read": "Lea la noticia",
  "updates.inEnglish": "Estas notas se publican en inglés.",

  // ---- highlights
  "hl.title": "Qué incluye la propuesta",
  "hl.levy": ({ since, first }) => (since ? `aumento del impuesto, el mayor desde ${since}` : `aumento del impuesto, el mayor desde por lo menos ${first}`),
  "hl.requestsFig": ({ below, total }) => `${below} de ${total}`,
  "hl.requests": (above) => `presupuestos quedaron por debajo de lo solicitado; ${above === 0 ? "ninguno quedó" : above === 1 ? "uno quedó" : `${num(above)} quedaron`} por encima`,
  "hl.admin": "para un puesto propuesto de administrador municipal",
  "hl.fees": (up) => `cambios de tarifas; ${up === 0 ? "ninguna sube" : up === 1 ? "una sube" : `${num(up)} suben`}`,

  // ---- reader-facing fund labels: [label, description, short form for the flow]
  "fund.General Fund.label": "Servicios diarios",
  "fund.General Fund.desc": "Policía, bomberos, calles, parques y oficinas municipales",
  "fund.General Fund.short": "Servicios",
  "fund.Debt Service Fund.label": "Pagos de deuda",
  "fund.Debt Service Fund.desc": "Capital e intereses del dinero que la ciudad ha pedido prestado",
  "fund.Debt Service Fund.short": "Deuda",
  "fund.MetroRide Fund.label": "Metro Ride",
  "fund.MetroRide Fund.desc": "El sistema de autobuses de la ciudad",
  "fund.MetroRide Fund.short": "Metro",
  "fund.Recycling Fund.label": "Reciclaje",
  "fund.Recycling Fund.desc": "Recolección de reciclaje en la acera",
  "fund.Recycling Fund.short": "Reciclaje",
  "fund.Central Equipment Capital Fund.label": "Equipo y obras menores en edificios",
  "fund.Central Equipment Capital Fund.desc": "Cámaras, radios y chalecos de la policía; computadoras y teléfonos; reparaciones menores en edificios",
  "fund.Central Equipment Capital Fund.short": "Equipo",
  "fund.Community Development.label": "Desarrollo comunitario",
  "fund.Community Development.desc": "Programas de planificación, desarrollo económico y vivienda",
  "fund.Community Development.short": "Desarrollo",
  "fund.Capital Projects Fund.label": "Calles y construcción",
  "fund.Capital Projects Fund.desc": "La parte financiada con impuestos de los proyectos de calles, aceras y edificios",
  "fund.Capital Projects Fund.short": "Calles",
  "fund.Wausau Downtown Airport Fund.label": "Aeropuerto del centro",
  "fund.Wausau Downtown Airport Fund.desc": "Operaciones del Wausau Downtown Airport",
  "fund.Wausau Downtown Airport Fund.short": "Aeropuerto",
  "fund.Parking Fund.label": "Estacionamiento",
  "fund.Parking Fund.desc": "Edificios y lotes de estacionamiento de la ciudad",
  "fund.Parking Fund.short": "Parqueo",
  "fund.Animal Control.label": "Control de animales",
  "fund.Animal Control.desc": "Servicios de control de animales",
  "fund.Animal Control.short": "Animales",
  "fund.tif.label": "Distritos de incremento de impuestos",
  "fund.tif.desc": "Impuestos sobre las nuevas construcciones en los distritos TIF de la ciudad, reservados para los costos de esos distritos",
  "fund.tif.short": "TIF",

  // ---- your bill
  "bill.title": (bill) => `Siga sus ${bill}`,
  "bill.standfirst": "Su impuesto municipal, a escala: primero los fondos que paga y luego cómo los servicios diarios lo reparten entre los departamentos. Pase el cursor sobre un bloque o tóquelo para ver su porcentaje.",
  "bill.flowShort": "Su impuesto",
  "bill.flowAria": ({ bill, funds, rest, depts }) => `Sus ${bill} de impuesto municipal: ${funds.map((f) => `${f.amount} para ${f.label.toLowerCase()}`).join(", ")} y el resto para otros ${rest} fondos más pequeños. De los servicios diarios: ${depts.map((d) => `${d.label.toLowerCase()} ${d.amount}`).join(", ")}. Todos los montos aparecen abajo.`,
  "bill.tipFund": "de su impuesto municipal",
  "bill.tipDept": "de los servicios diarios",
  "bill.flowNote": "La fila de abajo reparte los servicios diarios según la parte de cada departamento en el gasto del fondo general. La ciudad junta los impuestos a la propiedad con la ayuda estatal y las tarifas; no asigna dólares de impuestos a departamentos específicos.",
  "bill.preliminary": ({ year, growth }) => <><b>La tasa de {year} es preliminar.</b> Se basa en la cifra provisional que la ciudad usa para el valor tasado de {year} (el del año pasado más {growth}), que cambiará cuando el estado publique las cifras finales.</>,
  "bill.receiptTitle": "Cada línea de su impuesto municipal",
  "bill.receiptTotal": (year) => `Parte de la ciudad en su factura de ${year}`,
  "bill.receiptNote": (year) => `Cada línea es la parte de ese fondo en el impuesto total de la ciudad para ${year}, incluidos los distritos de incremento de impuestos. Las líneas están redondeadas al centavo, así que su suma puede diferir del total por unos centavos.`,
  "bill.cityOnly": <><b>Esta es solo la parte de la ciudad en su factura.</b> Su factura completa de impuestos a la propiedad también incluye al condado de Marathon, a su distrito escolar y al colegio técnico, cuyas tasas se fijan a mediados de noviembre. Ambos años usan el mismo valor tasado; si su tasación cambió, su cambio real será distinto.</>,

  // ---- shared bits
  "change.new": "nuevo",
  "change.none": "sin cambio",
  "table.year": "Año",
  "table.total": "Total",
  "table.change": "Cambio",

  // ---- levy
  "levy.title": "A dónde va el impuesto, año por año",
  "levy.standfirst": ({ total, year, up, pct, prev, first, grown }) => `La ciudad planea recaudar ${total} en impuestos a la propiedad para ${year}, un aumento de ${up} (${pct}) frente a ${prev}. Desde ${first}, el impuesto ha crecido un ${grown}.`,
  "levy.otherFunds": "Todos los demás fondos",
  "levy.totalLabel": "Impuesto total",
  "levy.chartAria": ({ first, last, from, to }) => `Gráfico de columnas apiladas del impuesto a la propiedad de la ciudad por año, de ${first} a ${last}, que sube de ${from} a ${to}. Las mismas cifras están en la tabla de abajo.`,
  "levy.tableTitle": "Impuesto total por año",
  "levy.colTotal": "Impuesto total",
  "levy.fundsTitle": "Todos los fondos que financia el impuesto",
  "levy.fundsNote": ({ first, last, year }) => `Las barras muestran de ${first} a ${last}, cada fila en su propia escala. El monto es el impuesto de ${year}.`,
  "levy.sparkAria": ({ label, first, last }) => `${label}, de ${first} a ${last}`,
  "levy.noneSince": (year) => `nada desde ${year}`,
  "levy.limitTitle": "El límite estatal, y lo que deja fuera",
  "levy.limitBody": ({ year, allowable, debt, actual }) => `Wisconsin limita cuánto puede crecer el impuesto de una ciudad, pero los pagos de dinero prestado están exentos. Para ${year}, el límite permite ${allowable}, más ${debt} para pagos de deuda. El impuesto propuesto, sin contar los distritos de incremento de impuestos, es de ${actual}.`,

  // ---- general fund
  "gf.title": <>El presupuesto del <span className="nowrap">día a día</span> de la ciudad</>,
  "gf.standfirst": ({ tax, share }) => `El fondo general paga la policía, los bomberos, las calles, los parques y las oficinas municipales. Los impuestos a la propiedad aportan ${tax}, cerca del ${share} de sus ingresos.`,
  "gf.spending": "Gasto",
  "gf.revenue": "Ingresos",
  "gf.gap": "Gasto menos ingresos",
  "gf.from": (year) => `frente a ${year}`,
  "gf.gapNote": "el gasto previsto supera los ingresos",
  "gf.viewAria": "Vista del fondo general",
  "gf.colDept": "Departamento",
  "gf.colSource": "Fuente",
  "gf.colProposed": (year) => `Propuesto ${year}`,
  "gf.colShare": "Parte",
  "gf.colVs": (year) => `vs. ${year}`,
  "gf.noteSpending": ({ year, prev }) => `Gasto propuesto para ${year} comparado con el presupuesto adoptado de ${prev}. Las cifras completas de cada departamento están en la siguiente sección.`,
  "gf.noteRevenue": ({ year, prev }) => `Ingresos propuestos para ${year} comparados con el presupuesto adoptado de ${prev}.`,
  "ogg.note": (cost) => `Costos de toda la ciudad que no se asignan a un departamento, incluidos ${cost} para un puesto propuesto de administrador municipal. Su página del presupuesto también incluye los ingresos generales del fondo general, entre ellos el impuesto a la propiedad, con los que se pagan todos los departamentos. Esta oficina no genera ese dinero.`,

  // ---- departments
  "dept.title": "Lo que pidió cada departamento, y lo que obtuvo",
  "dept.standfirst": ({ n, current, budget }) => `Los ${n} presupuestos de departamentos y fondos del libro presupuestario. Abra uno para ver su presupuesto de ${current}, su solicitud para ${budget}, el monto propuesto, a dónde va el dinero y unos 10 años de gasto presupuestado y real.`,
  "dept.searchLabel": "Busque un departamento o fondo por su nombre en inglés",
  "dept.searchPlaceholder": "Police, Water, Parks…",
  "dept.noMatch": (q) => <>Ningún departamento o fondo coincide con &ldquo;{q}&rdquo;.</>,
  "group.General Fund": "El principal presupuesto operativo de la ciudad: policía, bomberos, obras públicas, parques y oficinas municipales. Aquí va la mayor parte del impuesto a la propiedad.",
  "group.Special Revenue Funds": "Dinero reservado para un fin específico, como el reciclaje, el impuesto hotelero o las subvenciones de desarrollo comunitario.",
  "group.Debt Service Fund": "Pagos de la deuda de obligación general de la ciudad, que está respaldada por los impuestos a la propiedad.",
  "group.Capital Projects Funds": "Construcción y equipo, además del gasto de los distritos de incremento de impuestos en desarrollo.",
  "group.Internal Service Funds": "Cuentas que cobran a otros departamentos de la ciudad por vehículos, seguros y beneficios de los empleados. Esos mismos dólares también aparecen en los departamentos a los que cobran.",
  "group.Enterprise Funds": "Servicios pagados en gran parte por quienes los usan: agua, alcantarillado, autobuses, estacionamiento y el aeropuerto.",
  "dept.colBudget": "Presupuesto",
  "dept.adopted": (year) => `Adoptado ${year}`,
  "dept.requested": (year) => `Solicitado ${year}`,
  "dept.proposed": (year) => `Propuesto ${year}`,
  "dept.reqNothing": (amount) => `No se solicitó nada. El presupuesto propuesto incluye ${amount}.`,
  "dept.reqSame": "El presupuesto propuesto coincide con la solicitud.",
  "dept.reqChanged": ({ diff, pct, dir }) => `Cambio respecto a la solicitud: ${diff} (${pct} ${dir === "below" ? "por debajo de" : "por encima de"} la solicitud).`,
  "dept.spending": "Gasto",
  "dept.revenue": "Ingresos",
  "dept.colCategory": "Categoría",
  "dept.noRevenue": "Este presupuesto no tiene tabla de ingresos.",
  "dept.page": ({ printed, pdf }) => <>Vea la página de la ciudad: página {printed} del libro presupuestario (página {pdf} del PDF).</>,
  "dept.totalNote": ({ n, total }) => `En conjunto, los ${n} presupuestos proponen ${total} en gastos. Ese total cuenta algunos dólares dos veces: el dinero que pasa de un fondo de la ciudad a otro y los fondos de servicios internos que cobran a otros departamentos se cuentan en ambos lugares.`,

  // ---- 10-year history (inside each department)
  "hist.title": ({ first, last }) => <>Presupuesto y gasto real, <span className="nowrap">{first}&ndash;{last}</span></>,
  "hist.budget": "Presupuesto modificado",
  "hist.actual": "Gasto real",
  "hist.proposed": (year) => `Propuesto ${year}`,
  "hist.aria": ({ name, first, last, year, proposed }) => `${name}: presupuesto y gasto real, de ${first} a ${last}, medidos a partir del gráfico de la ciudad, con la propuesta de ${proposed} para ${year}. Las mismas cifras están en la tabla debajo del gráfico.`,
  "hist.approx": (page) => `Aproximado: medido a partir del gráfico de la ciudad en la página ${page} del libro presupuestario.`,
  "hist.check": ({ year, measured, table }) => ` Como comprobación, el gasto real de ${year} medido en el gráfico es de unos ${measured}; la tabla del presupuesto de la ciudad dice ${table}.`,
  "hist.flagCheck": ({ year, measured, table }) => `El gasto real de ${year} medido en el gráfico es de unos ${measured}; la tabla del presupuesto de la ciudad dice ${table}. `,
  "hist.showTable": "Ver como tabla",
  "hist.tableAria": (name) => `${name}: presupuesto y gasto real por año`,
  "hist.colBudget": "Presupuesto (aprox.)",
  "hist.colActual": "Real (aprox.)",
  "hist.none": "ninguno",
  "hist.tipBudget": "Presupuesto",
  "hist.tipActual": "Real",

  // ---- fees
  "fees.title": (year) => `Tarifas que cambian en ${year}`,
  "fees.standfirst": ({ total, up, down, removed, restructured }) => {
    const clauses = [
      [up, (n) => (n === 1 ? "una sube" : `${num(n)} suben`)],
      [down, (n) => (n === 1 ? "una baja" : `${num(n)} bajan`)],
      [removed, (n) => (n === 1 ? "se elimina una" : `se eliminan ${num(n)}`)],
      [restructured, (n) => (n === 1 ? "un pase cambia a un precio fijo" : `${num(n)} pases cambian a un precio fijo`)],
    ].filter(([n]) => n).map(([n, say]) => say(n));
    const kinds = clauses.length > 1 ? `${clauses.slice(0, -1).join(", ")} y ${clauses[clauses.length - 1]}` : clauses[0];
    return `La lista de tarifas propuesta cambia ${total} ${total === 1 ? "tarifa" : "tarifas"}: ${kinds}. La mayoría son permisos de estacionamiento y alquileres en parques, piscinas y para eventos.`;
  },
  "fees.leadTitle": "Mayores aumentos, en porcentaje",
  "fees.colFee": "Tarifa",
  "fees.colRates": ({ prev, year }) => `${prev} → ${year}`,
  "fees.colChange": "Cambio",
  "fees.count": ({ n, up }) => `${n} ${n === 1 ? "cambio" : "cambios"}${up !== n ? `, ${up} al alza` : ""}`,
  "fees.to": "a",
  "fees.none": "ninguna",
  "fees.discounts": "descuentos",
  "fees.dropped": "eliminada",
  "fees.flat": "precio fijo",
  "fees.was": ({ year, text }) => `En ${year}: “${text}”`,
  "fees.unclearTitle": "Poco claro en la lista de tarifas de la ciudad",
  "fees.problemsTitle": "Problemas en la lista de tarifas de la ciudad",
  "fees.page": (page) => `(Página ${page}.)`,
  "fees.note": ({ range, prev, year }) => `De las listas de tarifas de las páginas ${range} del libro presupuestario. Wausau Pilot & Review comparó cada fila, ${prev} frente a ${year}, y verificó cada cambio con la página impresa. No se incluyen las tarifas que no cambiaron.`,
  "feeGroup.Public works charges": "Cargos de obras públicas",
  "feeGroup.Parking": "Estacionamiento",
  "feeGroup.Finance and pet licenses": "Finanzas y licencias de mascotas",
  "feeGroup.Parks, pools and events": "Parques, piscinas y eventos",
  "feeGroup.Police": "Policía",

  // ---- capital projects
  "cap.title": "Lo que la ciudad planea construir y comprar",
  "cap.standfirst": ({ count, total, year, deferred, deferredTotal }) => `El presupuesto propuesto financia ${count} proyectos detallados que suman ${total} en ${year}. Otras ${deferred} solicitudes, por un valor de ${deferredTotal}, quedaron fuera.`,
  "cap.gap": ({ printed, diff, sum, page, context }) => <><b>Una diferencia en la lista de la ciudad.</b> El total impreso, {printed}, es {diff} mayor que la suma de los proyectos de la lista, que es de {sum} (página {page} del libro presupuestario). {context}</>,
  "discrepancy.capital projects: Infrastructure": "La diferencia equivale al costo de la reconstrucción de Ethel Street, que aparece solo en una segunda copia de esta lista, más adelante en el libro.",
  "cap.fundingTitle": "Cómo se pagan los proyectos",
  "cap.fundingNote": ({ total, page }) => `Fuentes de financiamiento tal como las enumera la ciudad, que suman ${total} (página ${page} del libro presupuestario).`,
  "cap.deferredTitle": "Solicitados, pero fuera del presupuesto",
  "cap.deferredNote": ({ total, page }) => `Proyectos que los departamentos pidieron y que no están en el presupuesto propuesto: ${total} en total (página ${page} del libro presupuestario).`,

  // ---- debt
  "debt.title": "Lo que debe la ciudad, y quién lo paga",
  "debt.standfirst": ({ total, asOf, go, rate }) => `La ciudad debía ${total} al ${asOf}. Los contribuyentes del impuesto a la propiedad respaldan ${go} de esa deuda; los clientes de agua y alcantarillado pagan los otros ${rate} mediante sus tarifas de servicio.`,
  "debt.taxBacked": "Respaldada por los impuestos a la propiedad",
  "debt.taxBackedNote": ({ undrawn, counted }) => `Deuda de obligación general desembolsada hasta ahora. Al sumar ${undrawn} en préstamos estatales aprobados pero aún no desembolsados, ${counted} cuentan para el límite legal de endeudamiento de la ciudad.`,
  "debt.rateBacked": "Pagada por los clientes de agua y alcantarillado",
  "debt.water": "Servicio de agua",
  "debt.sewer": "Servicio de alcantarillado",
  "debt.rateNote": "Deuda de ingresos, que se paga con las facturas de servicios y no con el impuesto a la propiedad.",
  "debt.limitTitle": "El límite legal",
  "debt.meterAria": ({ counted, limit, pct }) => `${counted} de un límite de ${limit}; se ha usado el ${pct}`,
  "debt.counted": ({ counted, pct }) => <><b>{counted}</b> contabilizados ({pct})</>,
  "debt.limit": (limit) => <>Límite <b>{limit}</b></>,
  "debt.limitNote": (share) => `La ley estatal limita la deuda de obligación general de una ciudad al ${share} del valor igualado de sus propiedades. La deuda de ingresos de agua y alcantarillado no cuenta para el límite.`,
  "debt.payTitle": "Cómo se paga",
  "debt.payNote": ({ first, last, total, principal, interest, by, share }) => `Pagos programados de la deuda de obligación general, de ${first} a ${last}. En ${first}, la ciudad paga ${total}: ${principal} de capital y ${interest} de intereses. Para ${by}, la ciudad tiene previsto haber pagado el ${share} del capital.`,
  "debt.principal": "Capital",
  "debt.interest": "Interés",
  "debt.totalPayment": "Pago total",
  "debt.chartAria": ({ first, last, total }) => `Gráfico de columnas apiladas de los pagos programados de la deuda de obligación general de ${first} a ${last}, que bajan desde ${total} en ${first}. Las mismas cifras están en la tabla de abajo.`,
  "debt.showTable": "Ver el calendario de pagos como tabla",
  "debt.tableAria": "Calendario de pagos",

  // ---- staffing
  "staff.title": "Cuántas personas emplea la ciudad",
  "staff.standfirst": ({ now, year, prev, prevYear }) => `El presupuesto propuesto financia ${now} puestos equivalentes a tiempo completo en ${year}, frente a ${prev} en ${prevYear}.`,
  "staff.chartAria": ({ first, last }) => `Gráfico de columnas del total de puestos equivalentes a tiempo completo por año, de ${first} a ${last}.`,
  "staff.caveat": ({ oldest, council }) => `* ${oldest} no es comparable con los años posteriores: es el único año que cuenta a los ${council} concejales.`,
  "staff.byDept": "Por departamento",
  "staff.note": ({ first, last }) => `Las barras muestran de ${first} a ${last}, cada fila en su propia escala. Los años en blanco están en blanco en la tabla de la ciudad.`,
  "staff.sparkAria": ({ name, first, last }) => `${name}: puestos, de ${first} a ${last}`,
  "staff.onlyIn": (year) => `solo en ${year}`,
  "staff.notListed": "no figura",

  // ---- about
  "about.title": "Sobre estas cifras",
  "about.sourceT": "Fuente",
  "about.sourceD": ({ year, pages, url }) => <>El presupuesto propuesto de {year} de la Ciudad de Wausau, tal como se publicó en el paquete de {pages} páginas para el Comité de Finanzas de la ciudad. Las referencias de página en esta página usan los números impresos en el libro presupuestario. La ciudad publica sus documentos presupuestarios en su <a href={url} target="_blank" rel="noopener noreferrer">página de informes presupuestarios</a>.</>,
  "about.methodT": "Método",
  "about.methodD": (n) => `Wausau Pilot & Review extrajo cada tabla del libro y la cotejó con los totales que imprimió la ciudad y con las demás tablas del libro. Los ${n} presupuestos de departamentos y fondos suman exactamente los totales de toda la ciudad. Donde el libro se contradice, esta página lo indica.`,
  "about.historyT": "El historial de 10 años es aproximado",
  "about.historyD": "El libro muestra los presupuestos y gastos de años anteriores solo como gráficos. Las cifras anuales del historial de cada departamento se midieron a partir de esos dibujos, así que son cercanas, pero no exactas. Cada gráfico que se puede verificar coincide con la cifra de la propia ciudad para su último año, con un margen de una fracción del 1% de la escala del gráfico; los dos que no se pueden verificar están señalados.",
  "about.rateT": "La tasa es preliminar",
  "about.rateD": ({ year, rate, growth }) => `La tasa de ${year}, de ${rate} por $1,000, divide el impuesto entre la cifra provisional que la ciudad usa para el valor tasado de ${year}, que es el del año pasado más ${growth}. Cambiará cuando el estado publique los valores finales.`,
  "about.cityT": "Solo la parte de la ciudad",
  "about.cityD": "Su factura de impuestos a la propiedad también incluye al condado de Marathon, a su distrito escolar y al colegio técnico. Sus tasas se fijan a mediados de noviembre.",
  "about.allFundsT": (total) => `Por qué esta página no destaca los ${total}`,
  "about.allFundsD": "Es el gasto de la ciudad en todos sus fondos, pero cuenta algunos dólares dos veces: el dinero que pasa entre fondos de la ciudad y los fondos de servicios internos que cobran a otros departamentos por vehículos, seguros y beneficios. El impuesto y el fondo general son medidas más claras.",
  "about.finalT": "Aún no es definitivo",
  "about.finalD": "Estas son las propuestas de la alcaldía. El Comité de Finanzas y el Concejo Municipal pueden cambiarlas antes de que el concejo adopte el presupuesto. Los cambios se registrarán en la parte superior de esta página.",
  "about.correctionsT": "Correcciones",
  "about.correctionsD": (email) => <>¿Ve algún error? Escriba a <a href={`mailto:${email}`}>{email}</a>.</>,
  "about.dataT": "Los datos",
  "about.dataD": (base) => <>Descargue las <a href={`${base}budget.json`} download>cifras del presupuesto</a>, los <a href={`${base}fees.json`} download>cambios de tarifas</a> y el <a href={`${base}history.json`} download>historial de 10 años</a> (JSON).</>,

  // ---- support band and footer
  "support.title": <>Creado por <span className="nowrap">Wausau Pilot &amp; Review</span></>,
  "support.body": ({ pages, units }) => `Leímos el presupuesto de ${pages} páginas de la ciudad, cotejamos los ${units} presupuestos de departamentos y fondos con sus totales, y actualizaremos esta página a medida que el Comité de Finanzas y el Concejo Municipal cambien el plan. Wausau Pilot & Review es un medio de noticias sin fines de lucro, y el apoyo de nuestros lectores mantiene gratuitas herramientas como esta.`,
  "support.button": "Apoye nuestro periodismo",
  "support.meetings": "Siga las reuniones sobre el presupuesto",
  "foot.data.proposed": (year) => `Datos: presupuesto propuesto de ${year} de la Ciudad de Wausau. Se actualiza a mano a medida que se enmienda el presupuesto.`,
  "foot.notAffiliated": "No está afiliado a la Ciudad de Wausau ni cuenta con su respaldo.",
};
