import React from "react";

// Hmong (Hmoob Dawb, RPA). BETA: AI-drafted from en.jsx, pending community review.
// Terms follow wpr-budget's Hmong table: se/tus se (levy), se vaj tse, daim nyiaj txiag, lub zos (city), pom zoo (adopted), npaj tseg (proposed), thov (requested), lab (million); figures stay US style.

export default {
  // ---- formats
  "fmt.today": (date) => `${["Hnub Caiv", "Hnub Ib", "Hnub Ob", "Hnub Peb", "Hnub Plaub", "Hnub Tsib", "Hnub Rau"][date.getDay()]}, ${["Lub Ib Hlis", "Lub Ob Hlis", "Lub Peb Hlis", "Lub Plaub Hlis", "Lub Tsib Hlis", "Lub Rau Hli", "Lub Xya Hli", "Lub Yim Hli", "Lub Cuaj Hli", "Lub Kaum Hli", "Lub Kaum Ib Hlis", "Lub Kaum Ob Hlis"][date.getMonth()]} tim ${date.getDate()}, ${date.getFullYear()}`,
  "fmt.date": (ymd) => `${["Lub Ib Hlis", "Lub Ob Hlis", "Lub Peb Hlis", "Lub Plaub Hlis", "Lub Tsib Hlis", "Lub Rau Hli", "Lub Xya Hli", "Lub Yim Hli", "Lub Cuaj Hli", "Lub Kaum Hli", "Lub Kaum Ib Hlis", "Lub Kaum Ob Hlis"][ymd.m - 1]} tim ${ymd.d}, ${ymd.y}`,
  "fmt.millions": (n) => `${n < 0 ? "−" : ""}$${(Math.abs(n) / 1e6).toFixed(1)} lab`,
  "fmt.aboutMillions": (n) => `${n < 0 ? "−" : ""}$${(Math.abs(n) / 1e6).toFixed(2)} lab`,

  // ---- language
  "lang.label": "Hom lus",
  "lang.namesNote": "Cov npe uas lub zos tshaj tawm (chaw haujlwm, cov nyiaj, pawg nyiaj txiag, nqi them, haujlwm tsim kho) yog ua lus Askiv, raws li luam tawm.",
  "lang.betaTitle": "Lus Hmoob yog ib qho lus txhais los ntawm zej zog (beta).",
  "lang.betaBody": (email) => <>Tej zaum cov lus tseem tsis tau zoo. Qhia rau Wausau Pilot &amp; Review paub yam yuav tsum kho: <a href={`mailto:${email}`}>{email}</a>.</>,

  // ---- page states
  "load.loading": "Tab tom thauj daim nyiaj txiag…",
  "load.errorTitle": "Thauj tsis tau cov ntaub ntawv nyiaj txiag.",
  "load.errorBody": (email) => <>Rov thauj nplooj no los sim dua. Yog tseem muaj li no, email rau <a href={`mailto:${email}`}>{email}</a>.</>,
  "status.proposed": "Daim nyiaj txiag uas tus kav nroog npaj tseg. Tseem tsis tau pom zoo.",

  // ---- masthead and banner
  "flag.homeAria": "Nplooj thawj ntawm Wausau Pilot & Review",
  "banner.kicker": "Lub Zos Wausau",
  "banner.title": (year) => <>Follow the Money: Wausau daim nyiaj txiag xyoo {year}</>,
  "banner.dek": ({ levy, pct, spend }) => `Daim nyiaj txiag npaj tseg no yuav sau ${levy} se vaj tse, nce ${pct}, thiab siv ${spend} rau tub ceev xwm, tub tua hluav taws, txoj kev, tiaj ua si thiab city hall. Nov yog nws txhais li cas rau koj daim nqi se.`,
  "sponsor.presentedBy": "Nthuav los ntawm",

  // ---- calculator
  "calc.assessedLabel": "Koj vaj tse tus nqi ntsuas (assessed value)",
  "calc.example": "Qhov no yog piv txwv xwb. ",
  "calc.hint": "Siv tus nqi ntsuas uas nyob ntawm koj daim nqi se, tsis yog tus nqi muag (market value).",
  "calc.yourTax": (year) => `Koj cov se lub zos xyoo ${year}`,
  "calc.compare": ({ diff, prior, year }) => <><span className="calc-diff">{diff}</span> piv rau {prior} xyoo {year}</>,
  "calc.empty": "Sau tus nqi ntsuas uas nyob ntawm koj daim nqi se.",
  "calc.rate": ({ rate, dir, prev }) => `${rate} rau ib $1,000 tus nqi ntsuas, ${dir === "up" ? "nce ntawm" : dir === "down" ? "poob ntawm" : "zoo ib yam li"} ${prev}.`,
  "calc.jump": (bill) => `Saib koj ${bill} mus qhov twg`,
  "share.button": "Faib",
  "share.copied": "Theej qhov txuas lawm",
  "share.urlAria": "Qhov txuas los faib",
  "share.title": (year) => `Follow the Money: Wausau daim nyiaj txiag xyoo ${year}`,
  "share.text": ({ dir, home, diff, year }) => `Wausau daim nyiaj txiag npaj tseg rau xyoo ${year} yuav ua rau se lub zos ntawm ib lub tsev ${home} ${dir === "up" ? "nce" : "poob"} ${diff}. Saib nws txhais li cas rau koj lub tsev:`,

  // ---- section nav
  "nav.aria": "Cov ntu",
  "nav.bill": "Koj daim nqi",
  "nav.levy": "Tus se",
  "nav.general-fund": "General fund",
  "nav.departments": "Chaw haujlwm",
  "nav.fees": "Nqi them",
  "nav.capital": "Tsim kho",
  "nav.debt": "Nuj nqis",
  "nav.staffing": "Neeg ua haujlwm",
  "nav.about": "Txog cov lej",

  // ---- updates
  "updates.title": "Tej yam hloov tom qab daim nyiaj txiag npaj tseg",
  "updates.note": "Cov lej hauv qab no yog tus kav nroog daim nyiaj txiag npaj tseg. Cov no yog tej yam uas tau hloov txij thaum ntawd los, qhov tshiab tshaj ua ntej.",
  "updates.read": "Nyeem zaj xov xwm",

  // ---- highlights
  "hl.title": "Muaj dab tsi hauv daim nyiaj txiag npaj tseg",
  "hl.levy": ({ since, first }) => (since ? `tus se nce, nce ntau tshaj plaws txij xyoo ${since} los` : `tus se nce, nce ntau tshaj plaws txij yam tsawg kawg xyoo ${first} los`),
  "hl.requestsFig": ({ below, total }) => `${below} ntawm ${total}`, // "ntawm 41" stays on one line
  "hl.requests": (above) => `daim nyiaj txiag qis dua qhov tau thov; ${above} daim siab dua qhov thov`,
  "hl.admin": "rau ib tug tswj hwm lub zos (city administrator) uas npaj tseg",
  "hl.fees": (up) => `tus nqi them hloov; ${up} tus nce`,

  // ---- reader-facing fund labels: [label, description, short form for the flow]
  "fund.General Fund.label": "Kev pab cuam niaj hnub",
  "fund.General Fund.desc": "Tub ceev xwm, tub tua hluav taws, txoj kev, tiaj ua si thiab city hall",
  "fund.General Fund.short": "Niaj hnub",
  "fund.Debt Service Fund.label": "Them nuj nqis",
  "fund.Debt Service Fund.desc": "Tus nqi qiv thiab paj rau cov nyiaj uas lub zos tau qiv",
  "fund.Debt Service Fund.short": "Nuj nqis",
  "fund.MetroRide Fund.label": "Metro Ride",
  "fund.MetroRide Fund.desc": "Lub zos cov tsheb npav",
  "fund.MetroRide Fund.short": "Metro",
  "fund.Recycling Fund.label": "Khoom rov siv dua",
  "fund.Recycling Fund.desc": "Khaws cov khoom rov siv dua ntawm ntug kev",
  "fund.Recycling Fund.short": "Rov siv dua",
  "fund.Central Equipment Capital Fund.label": "Khoom siv thiab kho tsev me me",
  "fund.Central Equipment Capital Fund.desc": "Tub ceev xwm lub koob yees duab, xov tooj cua thiab tsho tiv thaiv; khoos phis tawj thiab xov tooj; kho tsev me me",
  "fund.Central Equipment Capital Fund.short": "Khoom siv",
  "fund.Community Development.label": "Txhim kho zej zog",
  "fund.Community Development.desc": "Kev npaj lub zos (planning), txhim kho kev lag luam thiab cov kev pab txog tsev nyob",
  "fund.Community Development.short": "Zej zog",
  "fund.Capital Projects Fund.label": "Kev tsheb thiab kev tsim kho",
  "fund.Capital Projects Fund.desc": "Feem uas se them rau cov haujlwm txoj kev, kev taug kev thiab tsev",
  "fund.Capital Projects Fund.short": "Kev tsheb",
  "fund.Wausau Downtown Airport Fund.label": "Tshav dav hlau hauv plawv zos",
  "fund.Wausau Downtown Airport Fund.desc": "Kev khiav Wausau Downtown Airport",
  "fund.Wausau Downtown Airport Fund.short": "Dav hlau",
  "fund.Parking Fund.label": "Chaw nres tsheb",
  "fund.Parking Fund.desc": "Lub zos cov tsev nres tsheb thiab tshav nres tsheb",
  "fund.Parking Fund.short": "Nres tsheb",
  "fund.Animal Control.label": "Saib xyuas tsiaj",
  "fund.Animal Control.desc": "Kev pab saib xyuas tsiaj (animal control)",
  "fund.Animal Control.short": "Tsiaj",
  "fund.tif.label": "Cov cheeb tsam TIF",
  "fund.tif.desc": "Se ntawm tej vaj tse tshiab hauv lub zos cov cheeb tsam TIF, khaws cia them rau cov cheeb tsam ntawd tej nqi",
  "fund.tif.short": "TIF",

  // ---- your bill
  "bill.title": (bill) => `Taug qab koj ${bill}`,
  "bill.standfirst": "Koj cov se lub zos, raws qhov loj me tiag: ua ntej yog cov nyiaj (funds) uas nws them rau, ces kev pab cuam niaj hnub faib nws rau cov chaw haujlwm li cas. Coj nas mus rau los yog nias ib lub plaub fab kom pom nws feem.",
  "bill.flowShort": "Koj cov se lub zos",
  "bill.flowAria": ({ bill, funds, rest, depts }) => `Koj cov se lub zos ${bill}: ${funds.map((f) => `${f.amount} mus rau ${f.label.toLowerCase()}`).join(", ")}, thiab qhov seem mus rau ${rest} lub nyiaj me dua. Ntawm kev pab cuam niaj hnub, ${depts.map((d) => `${d.label.toLowerCase()} ${d.amount}`).join(", ")}. Txhua tus nqi muaj teev hauv qab no.`,
  "bill.tipFund": "ntawm koj cov se lub zos",
  "bill.tipDept": "ntawm kev pab cuam niaj hnub",
  "bill.flowNote": "Kab hauv qab faib kev pab cuam niaj hnub raws txhua lub chaw haujlwm feem ntawm kev siv nyiaj general fund. Lub zos muab se vaj tse sib xyaw nrog nyiaj pab los ntawm lub xeev thiab cov nqi them; nws tsis muab nyiaj se faib rau ib lub chaw haujlwm twg.",
  "bill.preliminary": ({ year, growth }) => <><b>Tus nqi se xyoo {year} tseem tsis tau yog tus kawg.</b> Nws nyob ntawm lub zos tus lej ib ntus (placeholder) rau tus nqi ntsuas xyoo {year} (tus nqi xyoo tas los ntxiv {growth}), uas yuav hloov thaum lub xeev tshaj tawm cov lej kawg.</>,
  "bill.receiptTitle": "Txhua kab ntawm koj cov se lub zos",
  "bill.receiptTotal": (year) => `Lub zos feem ntawm koj daim nqi xyoo ${year}`,
  "bill.receiptNote": (year) => `Txhua kab yog lub nyiaj ntawd feem ntawm tag nrho tus se lub zos xyoo ${year}, suav nrog cov cheeb tsam TIF. Cov kab suav txog ib xees, yog li tej zaum lawv yuav txawv ntawm tus tag nrho ob peb xees.`,
  "bill.cityOnly": <><b>Qhov no tsuas yog lub zos feem ntawm koj daim nqi xwb.</b> Koj daim nqi se vaj tse tag nrho kuj muaj Marathon County, koj lub koog tsev kawm ntawv thiab lub tsev kawm technical college, uas lawv cov nqi se teem thaum nruab nrab Lub Kaum Ib Hlis. Ob xyoos siv tib tus nqi ntsuas; yog koj tus nqi ntsuas tau hloov lawm, koj qhov hloov tiag tiag yuav txawv.</>,

  // ---- shared bits
  "change.new": "tshiab",
  "change.none": "tsis hloov",
  "table.year": "Xyoo",
  "table.total": "Tag nrho",
  "table.change": "Hloov",

  // ---- levy
  "levy.title": "Tus se mus qhov twg, txhua xyoo",
  "levy.standfirst": ({ total, year, up, pct, prev, first, grown }) => `Lub zos npaj yuav sau ${total} se vaj tse rau xyoo ${year}, nce ${up} (${pct}) ntawm ${prev}. Txij xyoo ${first} los, tus se tau nce ${grown}.`,
  "levy.otherFunds": "Tag nrho lwm cov nyiaj",
  "levy.totalLabel": "Tus se tag nrho",
  "levy.chartAria": ({ first, last, from, to }) => `Daim duab kem sib tshooj qhia tus se vaj tse ntawm lub zos txhua xyoo, ${first} txog ${last}, nce ntawm ${from} mus rau ${to}. Cov lej zoo ib yam nyob hauv lub rooj hauv qab no.`,
  "levy.tableTitle": "Tus se tag nrho txhua xyoo",
  "levy.colTotal": "Tus se tag nrho",
  "levy.fundsTitle": "Txhua lub nyiaj uas tus se them rau",
  "levy.fundsNote": ({ first, last, year }) => `Cov kab duab qhia xyoo ${first} txog ${last}; txhua kab siv nws tus kheej qhov ntsuas. Tus nqi yog tus se xyoo ${year}.`,
  "levy.sparkAria": ({ label, first, last }) => `${label}, ${first} txog ${last}`,
  "levy.noneSince": (year) => `tsis muaj txij xyoo ${year} los`,
  "levy.limitTitle": "Lub xeev txoj kev txwv, thiab yam nws tsis suav",
  "levy.limitBody": ({ year, allowable, debt, actual }) => `Wisconsin txwv seb ib lub zos tus se nce tau npaum li cas, tab sis cov nyiaj them rov qab cov nyiaj qiv tsis raug txwv. Rau xyoo ${year}, txoj kev txwv pub ${allowable}, ntxiv ${debt} rau kev them nuj nqis. Tus se npaj tseg, tsis suav cov cheeb tsam TIF, yog ${actual}.`,

  // ---- general fund
  "gf.title": <>Lub zos daim nyiaj txiag <span className="nowrap">niaj hnub</span></>,
  "gf.standfirst": ({ tax, share }) => `Lub general fund them rau tub ceev xwm, tub tua hluav taws, txoj kev, tiaj ua si thiab city hall. Se vaj tse them ${tax} ntawm nws, kwv yees li ${share} ntawm nws cov nyiaj tau los.`,
  "gf.spending": "Kev siv",
  "gf.revenue": "Nyiaj tau los",
  "gf.gap": "Kev siv rho nyiaj tau los",
  "gf.from": (year) => `piv rau ${year}`,
  "gf.gapNote": "kev siv npaj tseg ntau dua nyiaj tau los",
  "gf.viewAria": "Saib general fund",
  "gf.colDept": "Chaw haujlwm",
  "gf.colSource": "Qhov chaw",
  "gf.colProposed": (year) => `Npaj tseg rau ${year}`,
  "gf.colShare": "Feem",
  "gf.colVs": (year) => `piv rau ${year}`,
  "gf.noteSpending": ({ year, prev }) => `Kev siv npaj tseg rau xyoo ${year} piv rau daim nyiaj txiag pom zoo xyoo ${prev}. Cov lej tag nrho rau txhua lub chaw haujlwm nyob hauv ntu tom ntej.`,
  "gf.noteRevenue": ({ year, prev }) => `Nyiaj tau los npaj tseg rau xyoo ${year} piv rau daim nyiaj txiag pom zoo xyoo ${prev}.`,
  "ogg.note": (cost) => `Cov nqi siv rau tag nrho lub zos uas tsis tau muab rau ib lub chaw haujlwm twg, suav nrog ${cost} rau ib tug tswj hwm lub zos (city administrator) uas npaj tseg. Nws nplooj nyiaj txiag kuj muaj lub general fund cov nyiaj tau los dav dav, suav nrog se vaj tse, uas them rau txhua lub chaw haujlwm. Cov nyiaj ntawd tsis yog lub chaw haujlwm no khwv tau.`,

  // ---- departments
  "dept.title": "Txhua lub chaw haujlwm thov dab tsi, thiab tau dab tsi",
  "dept.standfirst": ({ n, current, budget }) => `Tag nrho ${n} daim nyiaj txiag ntawm cov chaw haujlwm thiab cov nyiaj hauv phau ntawv. Qhib ib qho los saib nws daim nyiaj txiag xyoo ${current}, nws qhov thov rau xyoo ${budget}, tus nqi npaj tseg, cov nyiaj mus qhov twg, thiab kwv yees li 10 xyoo ntawm cov nyiaj teem tseg thiab cov nyiaj siv tiag.`,
  "dept.searchLabel": "Nrhiav ib lub chaw haujlwm los yog lub nyiaj (sau ua lus Askiv)",
  "dept.searchPlaceholder": "Police, water, parks…",
  "dept.noMatch": (q) => <>Tsis muaj lub chaw haujlwm los yog lub nyiaj twg phim &ldquo;{q}&rdquo;.</>,
  "group.General Fund": "Lub zos daim nyiaj txiag tseem ceeb rau kev khiav haujlwm: tub ceev xwm, tub tua hluav taws, Public Works, tiaj ua si thiab city hall. Feem ntau ntawm se vaj tse los rau ntawm no.",
  "group.Special Revenue Funds": "Nyiaj muab cais tseg rau ib lub hom phiaj tshwj xeeb, xws li khoom rov siv dua, se chav so (room tax) los yog nyiaj pab txhim kho zej zog.",
  "group.Debt Service Fund": "Kev them lub zos cov nuj nqis general obligation, uas se vaj tse yog tus lav.",
  "group.Capital Projects Funds": "Kev tsim kho thiab khoom siv, ntxiv rau cov nyiaj uas cov cheeb tsam TIF siv rau kev txhim kho.",
  "group.Internal Service Funds": "Cov nyiaj uas xa nqi rau lwm lub chaw haujlwm hauv lub zos rau tsheb, kev pov hwm thiab txiaj ntsig neeg ua haujlwm. Tib cov nyiaj ntawd kuj pom nyob hauv cov chaw haujlwm uas lawv xa nqi rau.",
  "group.Enterprise Funds": "Cov kev pab uas feem ntau yog cov neeg siv them: dej, dej phwj (sewer), tsheb npav, chaw nres tsheb thiab tshav dav hlau.",
  "dept.colBudget": "Nyiaj txiag",
  "dept.adopted": (year) => `Pom zoo rau ${year}`,
  "dept.requested": (year) => `Thov rau ${year}`,
  "dept.proposed": (year) => `Npaj tseg rau ${year}`,
  "dept.reqNothing": (amount) => `Tsis tau thov dab tsi. Daim nyiaj txiag npaj tseg muaj ${amount}.`,
  "dept.reqSame": "Daim nyiaj txiag npaj tseg phim qhov thov.",
  "dept.reqChanged": ({ diff, pct, dir }) => `Hloov ntawm qhov thov: ${diff} (${pct} ${dir === "below" ? "qis dua" : "siab dua"} qhov thov).`,
  "dept.spending": "Kev siv",
  "dept.revenue": "Nyiaj tau los",
  "dept.colCategory": "Pawg",
  "dept.noRevenue": "Daim nyiaj txiag no tsis muaj lub rooj nyiaj tau los.",
  "dept.page": ({ printed, pdf }) => <>Saib lub zos nplooj ntawv: nplooj {printed} hauv phau ntawv nyiaj txiag (nplooj {pdf} hauv daim PDF).</>,
  "dept.totalNote": ({ n, total }) => `Ua ke, ${n} daim nyiaj txiag npaj siv ${total}. Tus lej ntawd suav qee cov nyiaj ob zaug: nyiaj uas txav ntawm ib lub nyiaj ntawm lub zos mus rau lwm lub, thiab cov internal service funds uas xa nqi rau lwm lub chaw haujlwm, raug suav rau ob qho chaw.`,

  // ---- 10-year history (inside each department)
  "hist.title": ({ first, last }) => <>Nyiaj teem tseg thiab nyiaj siv tiag, <span className="nowrap">{first}&ndash;{last}</span></>,
  "hist.budget": "Nyiaj teem tseg, raws li tau hloov kho",
  "hist.actual": "Nyiaj siv tiag",
  "hist.proposed": (year) => `Npaj tseg rau ${year}`,
  "hist.aria": ({ name, first, last, year, proposed }) => `${name}: nyiaj teem tseg thiab nyiaj siv tiag, ${first} txog ${last}, ntsuas los ntawm lub zos daim duab, nrog rau qhov npaj tseg rau xyoo ${year} ntawm ${proposed}. Cov lej zoo ib yam nyob hauv lub rooj hauv qab daim duab.`,
  "hist.approx": (page) => `Kwv yees xwb: ntsuas los ntawm lub zos daim duab ntawm nplooj ${page} hauv phau ntawv nyiaj txiag.`,
  "hist.check": ({ year, measured, table }) => ` Txhawm rau kuaj, nws qhov siv tiag xyoo ${year} ntsuas tau li ${measured}; lub zos lub rooj nyiaj txiag hais tias ${table}.`,
  "hist.flagCheck": ({ year, measured, table }) => `Daim duab qhov siv tiag xyoo ${year} ntsuas tau li ${measured}; lub zos lub rooj nyiaj txiag hais tias ${table}. `,
  "hist.showTable": "Saib ua lub rooj",
  "hist.tableAria": (name) => `${name} nyiaj teem tseg thiab nyiaj siv tiag txhua xyoo`,
  "hist.colBudget": "Nyiaj teem tseg (kwv yees)",
  "hist.colActual": "Siv tiag (kwv yees)",
  "hist.none": "tsis muaj",
  "hist.tipBudget": "Nyiaj teem tseg",
  "hist.tipActual": "Siv tiag",

  // ---- fees
  "fees.title": (year) => `Cov nqi them uas hloov rau xyoo ${year}`,
  "fees.standfirst": ({ total, up, down, removed, restructured }) => {
    const clauses = [
      [up, "tus nce"], [down, "tus poob"],
      [removed, "tus raug tshem tawm"],
      [restructured, "daim pass hloov ua ib tus nqi ruaj"],
    ].filter(([n]) => n).map(([n, words]) => `${n} ${words}`);
    const kinds = clauses.length > 1 ? `${clauses.slice(0, -1).join(", ")} thiab ${clauses[clauses.length - 1]}` : clauses[0];
    return `Daim teev nqi them uas npaj tseg hloov ${total} tus nqi: ${kinds}. Feem ntau yog daim ntawv tso cai nres tsheb thiab kev xauj tiaj ua si, pas dej da thiab chaw ua koob tsheej.`;
  },
  "fees.leadTitle": "Cov nqi nce ntau tshaj plaws, raws feem pua",
  "fees.colFee": "Nqi them",
  "fees.colRates": ({ prev, year }) => `${prev} → ${year}`,
  "fees.colChange": "Hloov",
  "fees.count": ({ n, up }) => `${n} qhov hloov${up !== n ? `, ${up} nce` : ""}`,
  "fees.to": "mus rau",
  "fees.none": "tsis muaj",
  "fees.discounts": "luv nqi",
  "fees.dropped": "tshem tawm",
  "fees.flat": "nqi ruaj",
  "fees.was": ({ year, text }) => `Xyoo ${year}: “${text}”`,
  "fees.unclearTitle": "Tsis meej hauv lub zos daim teev nqi",
  "fees.problemsTitle": "Teeb meem hauv lub zos daim teev nqi",
  "fees.page": (page) => `(Nplooj ${page}.)`,
  "fees.note": ({ range, prev, year }) => `Los ntawm cov teev nqi them ntawm nplooj ${range} hauv phau ntawv nyiaj txiag. Wausau Pilot & Review tau piv txhua kab, ${prev} rau ${year}, thiab kuaj txhua qhov hloov nrog nplooj ntawv luam tawm. Cov nqi them uas tsis hloov tsis tau teev.`,
  "feeGroup.Public works charges": "Nqi them rau Public Works",
  "feeGroup.Parking": "Nres tsheb",
  "feeGroup.Finance and pet licenses": "Nyiaj txiag thiab ntawv tso cai rau tsiaj yug",
  "feeGroup.Parks, pools and events": "Tiaj ua si, pas dej da thiab koob tsheej",
  "feeGroup.Police": "Tub ceev xwm",

  // ---- capital projects
  "cap.title": "Yam lub zos npaj yuav tsim thiab yuav",
  "cap.standfirst": ({ count, total, year, deferred, deferredTotal }) => `Daim nyiaj txiag npaj tseg them rau ${count} txoj haujlwm tsim kho uas muaj teev, tag nrho ${total} rau xyoo ${year}. Lwm ${deferred} qhov thov, muaj nqis ${deferredTotal}, tsis tau muab tso rau hauv.`,
  "cap.gap": ({ printed, diff, sum, page, context }) => <><b>Ib qho sib txawv hauv lub zos daim ntawv teev.</b> Tus lej tag nrho luam tawm, {printed}, ntau dua {diff} tshaj cov haujlwm uas muaj teev, uas suav ua ke tau {sum} (nplooj {page} hauv phau ntawv nyiaj txiag). {context}</>,
  "discrepancy.capital projects: Infrastructure": "Qhov sib txawv ntawd sib npaug rau tus nqi rov tsim Ethel Street dua tshiab, uas tsuas muaj nyob hauv daim ntawv teev thib ob tom qab hauv phau ntawv.",
  "cap.fundingTitle": "Cov nyiaj them rau cov haujlwm los qhov twg",
  "cap.fundingNote": ({ total, page }) => `Cov chaw nyiaj los raws li lub zos teev, tag nrho ${total} (nplooj ${page} hauv phau ntawv nyiaj txiag).`,
  "cap.deferredTitle": "Tau thov tab sis tsis tau muab tso rau hauv",
  "cap.deferredNote": ({ total, page }) => `Cov haujlwm uas cov chaw haujlwm tau thov tab sis tsis nyob hauv daim nyiaj txiag npaj tseg: tag nrho ${total} (nplooj ${page} hauv phau ntawv nyiaj txiag).`,

  // ---- debt
  "debt.title": "Lub zos tshuav nuj npaum li cas, thiab leej twg them rov qab",
  "debt.standfirst": ({ total, asOf, go, rate }) => `Lub zos tshuav ${total} txog ${asOf}. Cov neeg them se vaj tse lav ${go} ntawm cov nuj ntawd; cov neeg siv dej thiab dej phwj them rov qab lwm ${rate} los ntawm lawv tus nqi dej thiab dej phwj.`,
  "debt.taxBacked": "Muaj se vaj tse lav",
  "debt.taxBackedNote": ({ undrawn, counted }) => `Nuj nqis general obligation uas tau rho los siv txog tam sim no. Suav ${undrawn} nyiaj qiv ntawm lub xeev uas pom zoo lawm tab sis tseem tsis tau rho, ${counted} raug suav rau lub zos qhov txwv qiv nyiaj raws txoj cai.`,
  "debt.rateBacked": "Cov neeg siv dej thiab dej phwj them rov qab",
  "debt.water": "Lub chaw muab dej",
  "debt.sewer": "Lub chaw tswj dej phwj",
  "debt.rateNote": "Nuj nqis revenue (revenue debt), them rov qab los ntawm daim nqi dej thiab dej phwj, tsis yog se vaj tse.",
  "debt.limitTitle": "Qhov txwv raws txoj cai",
  "debt.meterAria": ({ counted, limit, pct }) => `${counted} ntawm qhov txwv ${limit}, siv lawm ${pct}`,
  "debt.counted": ({ counted, pct }) => <><b>{counted}</b> raug suav ({pct})</>,
  "debt.limit": (limit) => <>Qhov txwv <b>{limit}</b></>,
  "debt.limitNote": (share) => `Txoj cai lub xeev txwv ib lub zos cov nuj nqis general obligation kom tsis pub tshaj ${share} ntawm nws tus nqi vaj tse equalized. Nuj nqis revenue ntawm dej thiab dej phwj tsis suav rau qhov txwv.`,
  "debt.payTitle": "Them rov qab",
  "debt.payNote": ({ first, last, total, principal, interest, by, share }) => `Cov nyiaj teem caij them rau nuj nqis general obligation, ${first} txog ${last}. Xyoo ${first} lub zos them ${total}: ${principal} tus nqi qiv thiab ${interest} paj. Txog xyoo ${by} lub zos teem caij yuav them rov qab ${share} ntawm tus nqi qiv.`,
  "debt.principal": "Tus nqi qiv",
  "debt.interest": "Paj",
  "debt.totalPayment": "Tag nrho qhov them",
  "debt.chartAria": ({ first, last, total }) => `Daim duab kem sib tshooj qhia cov nyiaj teem caij them nuj nqis general obligation txij ${first} txog ${last}, poob ntawm ${total} xyoo ${first}. Cov lej zoo ib yam nyob hauv lub rooj hauv qab no.`,
  "debt.showTable": "Saib daim teev caij them rov qab ua lub rooj",
  "debt.tableAria": "Daim teev caij them rov qab",

  // ---- staffing
  "staff.title": "Lub zos ntiav neeg ua haujlwm pes tsawg leej",
  "staff.standfirst": ({ now, year, prev, prevYear }) => `Daim nyiaj txiag npaj tseg them rau ${now} txoj haujlwm full-time-equivalent (suav raws li haujlwm puv sij hawm) xyoo ${year}, piv rau ${prev} xyoo ${prevYear}.`,
  "staff.chartAria": ({ first, last }) => `Daim duab kem qhia tag nrho txoj haujlwm full-time-equivalent txhua xyoo, ${first} txog ${last}.`,
  "staff.caveat": ({ oldest, council }) => `* Xyoo ${oldest} piv tsis tau rau cov xyoo tom qab: nws yog tib xyoo uas suav ${council} tus tswv cuab hauv pawg sab laj (council).`,
  "staff.byDept": "Raws chaw haujlwm",
  "staff.note": ({ first, last }) => `Cov kab duab qhia xyoo ${first} txog ${last}; txhua kab siv nws tus kheej qhov ntsuas. Cov xyoo khoob yog khoob hauv lub zos lub rooj.`,
  "staff.sparkAria": ({ name, first, last }) => `${name} txoj haujlwm, ${first} txog ${last}`,
  "staff.onlyIn": (year) => `tsuas yog xyoo ${year}`,
  "staff.notListed": "tsis tau teev",

  // ---- about
  "about.title": "Txog cov lej no",
  "about.sourceT": "Qhov chaw",
  "about.sourceD": ({ year, pages, url }) => <>Lub Zos Wausau daim nyiaj txiag npaj tseg rau xyoo {year}, raws li luam tawm hauv pob ntawv {pages} nplooj rau lub zos Finance Committee (pawg saib xyuas nyiaj txiag). Thaum nplooj no hais txog ib nplooj ntawv, nws siv tus lej nplooj uas luam tawm hauv phau ntawv nyiaj txiag. Lub zos muab nws cov ntaub ntawv nyiaj txiag tso rau ntawm nws <a href={url} target="_blank" rel="noopener noreferrer">nplooj ntawv qhia txog nyiaj txiag</a>.</>,
  "about.methodT": "Txoj kev ua",
  "about.methodD": (n) => `Wausau Pilot & Review tau rho txhua lub rooj tawm ntawm phau ntawv thiab kuaj txhua lub nrog cov lej tag nrho uas lub zos luam tawm thiab nrog phau ntawv lwm cov rooj. ${n} daim nyiaj txiag ntawm cov chaw haujlwm thiab cov nyiaj suav ua ke sib npaug nkaus rau cov lej tag nrho ntawm lub zos. Qhov twg phau ntawv hais tsis sib xws, nplooj no qhia meej.`,
  "about.historyT": "Keeb kwm 10 xyoo yog kwv yees xwb",
  "about.historyD": "Phau ntawv qhia cov nyiaj teem tseg thiab kev siv nyiaj yav dhau los ua daim duab xwb. Cov lej txhua xyoo hauv txhua lub chaw haujlwm keeb kwm tau ntsuas los ntawm cov duab ntawd, yog li lawv ze tab sis tsis yog tseeb tag. Txhua daim duab uas kuaj tau phim lub zos tus lej rau nws xyoo kawg, txawv tsis txog ib feem pua ntawm daim duab qhov ntsuas; ob daim uas kuaj tsis tau muaj lus qhia.",
  "about.rateT": "Tus nqi se tseem tsis tau yog tus kawg",
  "about.rateD": ({ year, rate, growth }) => `Tus nqi se xyoo ${year} ntawm ${rate} rau ib $1,000 yog muab tus se faib los ntawm lub zos tus lej ib ntus rau tus nqi ntsuas xyoo ${year}, uas yog tus nqi xyoo tas los ntxiv ${growth}. Nws yuav hloov thaum lub xeev tshaj tawm cov nqi kawg.`,
  "about.cityT": "Tsuas yog lub zos feem xwb",
  "about.cityD": "Koj daim nqi se vaj tse kuj muaj Marathon County, koj lub koog tsev kawm ntawv thiab lub tsev kawm technical college. Lawv cov nqi se teem thaum nruab nrab Lub Kaum Ib Hlis.",
  "about.allFundsT": (total) => `Vim li cas nplooj no tsis pib nrog ${total}`,
  "about.allFundsD": "Qhov ntawd yog lub zos kev siv nyiaj thoob plaws txhua lub nyiaj, tab sis nws suav qee cov nyiaj ob zaug: nyiaj txav ntawm lub zos ib lub nyiaj mus rau lwm lub, thiab cov internal service funds uas xa nqi rau lwm lub chaw haujlwm rau tsheb, kev pov hwm thiab txiaj ntsig. Tus se thiab lub general fund yog cov lej pom tseeb dua.",
  "about.finalT": "Tseem tsis tau yog qhov kawg",
  "about.finalD": "Cov no yog tus kav nroog tej kev npaj. Finance Committee (pawg saib xyuas nyiaj txiag) thiab Common Council (Pawg Sab Laj Nroog) hloov tau ua ntej pawg sab laj pom zoo daim nyiaj txiag. Tej yam hloov yuav sau tseg rau saum toj ntawm nplooj no.",
  "about.correctionsT": "Kho qhov yuam kev",
  "about.correctionsD": (email) => <>Pom ib yam dab tsi tsis yog? Email rau <a href={`mailto:${email}`}>{email}</a>.</>,
  "about.dataT": "Cov ntaub ntawv",
  "about.dataD": (base) => <>Rub <a href={`${base}budget.json`} download>cov lej nyiaj txiag</a>, <a href={`${base}fees.json`} download>cov nqi them uas hloov</a> thiab <a href={`${base}history.json`} download>keeb kwm 10 xyoo</a> (JSON).</>,

  // ---- support band and footer
  "support.title": <>Tsim los ntawm <span className="nowrap">Wausau Pilot &amp; Review</span></>,
  "support.body": ({ pages, units }) => `Peb tau nyeem lub zos daim nyiaj txiag ${pages} nplooj, kuaj tag nrho ${units} daim nyiaj txiag ntawm cov chaw haujlwm thiab cov nyiaj nrog nws cov lej tag nrho, thiab yuav hloov kho nplooj no thaum Finance Committee (pawg saib xyuas nyiaj txiag) thiab Common Council (Pawg Sab Laj Nroog) hloov txoj kev npaj. Wausau Pilot & Review yog ib lub chaw xov xwm tsis ua lag luam (nonprofit), thiab kev txhawb los ntawm cov neeg nyeem pab kom tej cuab yeej zoo li no pub dawb.`,
  "support.button": "Txhawb peb txoj kev sau xov xwm",
  "support.meetings": "Taug qab cov rooj sib tham txog nyiaj txiag",
  "foot.data.proposed": (year) => `Cov ntaub ntawv: Lub Zos Wausau daim nyiaj txiag npaj tseg rau xyoo ${year}. Peb hloov kho ntawm tes thaum daim nyiaj txiag raug hloov.`,
  "foot.notAffiliated": "Tsis muaj feem nrog Lub Zos Wausau, thiab Lub Zos Wausau tsis tau txhawb nqa.",
};
